#pragma once

#define CHILD_ID_LIGHT 0
#define LIGHT_PIN 6
#define BUTTON_PIN A1
#define LIGHT_BUTTON_PIN 5

#define CHILD_ID_UP 1
#define BUTTON_PIN_UP A0
#define LIGHT_BUTTON_PIN_UP 7
#define BUTTON_MOTOR_UP 2

#define CHILD_ID_DOWN 2
#define BUTTON_PIN_DOWN A2
#define LIGHT_BUTTON_PIN_DOWN 4
#define BUTTON_MOTOR_DOWN 3

